### ISSUE TITLE
nullPointer on drag-and-drop folder import

### ISSUE THREAD

**Issue by dstorch** [dstorch/CamScan#1]
I think this is related to GUI code, so Stelios, maybe you will be able to figure out what is happening. It's possible that a null pointer is being thrown from this line:

int newW = (int) (this.img.getWidth() \* this.scaleFactor);

Maybe img is null?

**Comment by dstorch** [comment]
I added a check for null in the ViewPanel.java class---there was a null pointer because img was null. Not sure how to really fix the GUI though Stelios, because pages won't display now when I import them

**Comment by sanagnos** [comment]
does it work now?
